/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121735-gbe99d2c0b2-20251111"
#endif /* AVUTIL_FFVERSION_H */
